name: bamboo_finances
description: Bamboo is a streamlined personal finance app, designed exclusively for individuals. It offers intuitive expense tracking, customizable budgeting, and bill management, empowering users to take control of their financial well-being with ease and confidence. Download Bamboo to simplify your money management today.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  # Firebase
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5

  # Fonts
  google_fonts: ^6.0.0

  flutter:
    sdk: flutter

  # Splash Page
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
 
  assets: 
    - res/fonts/
  uses-material-design: true
